### ISSUE TITLE
AccessModes filtering

### ISSUE THREAD

**Issue by michaelfig** [torchbox/k8s-hostpath-provisioner#1]
First, thanks so much for this project: it does almost exactly what I need it to!  I'm using it to provision non-networked local disk hostpath pvcs in a single-node cluster.

I would only like one new feature: the ability to limit the accessMode of the requesting pvc.  This would make the storage class safer for my use case, by being able to specify which accessModes the storage class supports, and have the provisioner reject other accessModes.

Here is my desired YAML for my default (local disk) storage class, where I would like to reject ReadWriteMany and ReadOnlyMany accessModes:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: torchbox.com/hostpath
parameters:
  accessModes:
    - ReadWriteOnce
  pvDir: /volumes
```

This seems like an easy change, but I don't know Go well enough to send a pull request, and it's definitely not blocking my use of hostpath-provisioner.

Thanks again,
Michael.
